### ISSUE TITLE
Kotlin version

### ISSUE THREAD

**Issue by jarkoAndroid** [nhaarman/mockito-kotlin#51]
looks like your lib can be build only with Kotlin 1.0.2, but the actual version of Kotlin is 1.0.3

**Comment by jonathanbergen** [comment]
Should be fixed with #44.

**Comment by jarkoAndroid** [comment]
Houston we still have a problem here: 

testCompile "com.nhaarman:mockito-kotlin:0.5.1"

Error:Conflict with dependency 'org.jetbrains.kotlin:kotlin-stdlib'. Resolved versions for app (1.0.3) and test app (1.0.2-1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Error:Conflict with dependency 'org.jetbrains.kotlin:kotlin-runtime'. Resolved versions for app (1.0.3) and test app (1.0.2-1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

**Comment by jonathanbergen** [comment]
Yes, as long as mockito-kotlin depends on kotlin 1.0.2-1 you get this dependency conflict. 
You have three options for now:

1. Wait until mockito-kotlin updates to 1.0.3
2. Downgrade your kotlin version to 1.0.2-1
3. Create your own fork of mockito-kotlin with kotlin 1.0.3
